/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsSlugRouteImport } from './routes/posts/$slug'
import { Route as ApiV1ProfileIndexRouteImport } from './routes/api/v1/profile/index'
import { Route as ApiV1PasskeysIndexRouteImport } from './routes/api/v1/passkeys/index'
import { Route as ApiV1VisitorWeatherRouteImport } from './routes/api/v1/visitor/weather'
import { Route as ApiV1ProfileSendCodeRouteImport } from './routes/api/v1/profile/send-code'
import { Route as ApiV1PasskeysIdRouteImport } from './routes/api/v1/passkeys/$id'
import { Route as ApiV1CommentsBatchRouteImport } from './routes/api/v1/comments/batch'
import { Route as ApiV1CommentsIdRouteImport } from './routes/api/v1/comments/$id'
import { Route as ApiV1AuthResetPasswordRouteImport } from './routes/api/v1/auth/reset-password'
import { Route as ApiV1AuthRefreshRouteImport } from './routes/api/v1/auth/refresh'
import { Route as ApiV1AuthPasswordRouteImport } from './routes/api/v1/auth/password'
import { Route as ApiV1AuthMeRouteImport } from './routes/api/v1/auth/me'
import { Route as ApiV1AuthLogoutRouteImport } from './routes/api/v1/auth/logout'
import { Route as ApiV1AuthLoginRouteImport } from './routes/api/v1/auth/login'
import { Route as ApiV1AuthForgotPasswordRouteImport } from './routes/api/v1/auth/forgot-password'
import { Route as ApiV1AuthTotpActionRouteImport } from './routes/api/v1/auth/totp/$action'
import { Route as ApiV1AuthPasskeyAvailableRouteImport } from './routes/api/v1/auth/passkey/available'
import { Route as ApiV1AuthPasskeyFlowActionRouteImport } from './routes/api/v1/auth/passkey/$flow/$action'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProfileIndexRoute = ApiV1ProfileIndexRouteImport.update({
  id: '/api/v1/profile/',
  path: '/api/v1/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PasskeysIndexRoute = ApiV1PasskeysIndexRouteImport.update({
  id: '/api/v1/passkeys/',
  path: '/api/v1/passkeys/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1VisitorWeatherRoute = ApiV1VisitorWeatherRouteImport.update({
  id: '/api/v1/visitor/weather',
  path: '/api/v1/visitor/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProfileSendCodeRoute = ApiV1ProfileSendCodeRouteImport.update({
  id: '/api/v1/profile/send-code',
  path: '/api/v1/profile/send-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PasskeysIdRoute = ApiV1PasskeysIdRouteImport.update({
  id: '/api/v1/passkeys/$id',
  path: '/api/v1/passkeys/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CommentsBatchRoute = ApiV1CommentsBatchRouteImport.update({
  id: '/api/v1/comments/batch',
  path: '/api/v1/comments/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CommentsIdRoute = ApiV1CommentsIdRouteImport.update({
  id: '/api/v1/comments/$id',
  path: '/api/v1/comments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthResetPasswordRoute = ApiV1AuthResetPasswordRouteImport.update({
  id: '/api/v1/auth/reset-password',
  path: '/api/v1/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthRefreshRoute = ApiV1AuthRefreshRouteImport.update({
  id: '/api/v1/auth/refresh',
  path: '/api/v1/auth/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthPasswordRoute = ApiV1AuthPasswordRouteImport.update({
  id: '/api/v1/auth/password',
  path: '/api/v1/auth/password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthMeRoute = ApiV1AuthMeRouteImport.update({
  id: '/api/v1/auth/me',
  path: '/api/v1/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthLogoutRoute = ApiV1AuthLogoutRouteImport.update({
  id: '/api/v1/auth/logout',
  path: '/api/v1/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthLoginRoute = ApiV1AuthLoginRouteImport.update({
  id: '/api/v1/auth/login',
  path: '/api/v1/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthForgotPasswordRoute = ApiV1AuthForgotPasswordRouteImport.update({
  id: '/api/v1/auth/forgot-password',
  path: '/api/v1/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthTotpActionRoute = ApiV1AuthTotpActionRouteImport.update({
  id: '/api/v1/auth/totp/$action',
  path: '/api/v1/auth/totp/$action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthPasskeyAvailableRoute =
  ApiV1AuthPasskeyAvailableRouteImport.update({
    id: '/api/v1/auth/passkey/available',
    path: '/api/v1/auth/passkey/available',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AuthPasskeyFlowActionRoute =
  ApiV1AuthPasskeyFlowActionRouteImport.update({
    id: '/api/v1/auth/passkey/$flow/$action',
    path: '/api/v1/auth/passkey/$flow/$action',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/api/v1/auth/forgot-password': typeof ApiV1AuthForgotPasswordRoute
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/me': typeof ApiV1AuthMeRoute
  '/api/v1/auth/password': typeof ApiV1AuthPasswordRoute
  '/api/v1/auth/refresh': typeof ApiV1AuthRefreshRoute
  '/api/v1/auth/reset-password': typeof ApiV1AuthResetPasswordRoute
  '/api/v1/comments/$id': typeof ApiV1CommentsIdRoute
  '/api/v1/comments/batch': typeof ApiV1CommentsBatchRoute
  '/api/v1/passkeys/$id': typeof ApiV1PasskeysIdRoute
  '/api/v1/profile/send-code': typeof ApiV1ProfileSendCodeRoute
  '/api/v1/visitor/weather': typeof ApiV1VisitorWeatherRoute
  '/api/v1/passkeys/': typeof ApiV1PasskeysIndexRoute
  '/api/v1/profile/': typeof ApiV1ProfileIndexRoute
  '/api/v1/auth/passkey/available': typeof ApiV1AuthPasskeyAvailableRoute
  '/api/v1/auth/totp/$action': typeof ApiV1AuthTotpActionRoute
  '/api/v1/auth/passkey/$flow/$action': typeof ApiV1AuthPasskeyFlowActionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/api/v1/auth/forgot-password': typeof ApiV1AuthForgotPasswordRoute
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/me': typeof ApiV1AuthMeRoute
  '/api/v1/auth/password': typeof ApiV1AuthPasswordRoute
  '/api/v1/auth/refresh': typeof ApiV1AuthRefreshRoute
  '/api/v1/auth/reset-password': typeof ApiV1AuthResetPasswordRoute
  '/api/v1/comments/$id': typeof ApiV1CommentsIdRoute
  '/api/v1/comments/batch': typeof ApiV1CommentsBatchRoute
  '/api/v1/passkeys/$id': typeof ApiV1PasskeysIdRoute
  '/api/v1/profile/send-code': typeof ApiV1ProfileSendCodeRoute
  '/api/v1/visitor/weather': typeof ApiV1VisitorWeatherRoute
  '/api/v1/passkeys': typeof ApiV1PasskeysIndexRoute
  '/api/v1/profile': typeof ApiV1ProfileIndexRoute
  '/api/v1/auth/passkey/available': typeof ApiV1AuthPasskeyAvailableRoute
  '/api/v1/auth/totp/$action': typeof ApiV1AuthTotpActionRoute
  '/api/v1/auth/passkey/$flow/$action': typeof ApiV1AuthPasskeyFlowActionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/api/v1/auth/forgot-password': typeof ApiV1AuthForgotPasswordRoute
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/me': typeof ApiV1AuthMeRoute
  '/api/v1/auth/password': typeof ApiV1AuthPasswordRoute
  '/api/v1/auth/refresh': typeof ApiV1AuthRefreshRoute
  '/api/v1/auth/reset-password': typeof ApiV1AuthResetPasswordRoute
  '/api/v1/comments/$id': typeof ApiV1CommentsIdRoute
  '/api/v1/comments/batch': typeof ApiV1CommentsBatchRoute
  '/api/v1/passkeys/$id': typeof ApiV1PasskeysIdRoute
  '/api/v1/profile/send-code': typeof ApiV1ProfileSendCodeRoute
  '/api/v1/visitor/weather': typeof ApiV1VisitorWeatherRoute
  '/api/v1/passkeys/': typeof ApiV1PasskeysIndexRoute
  '/api/v1/profile/': typeof ApiV1ProfileIndexRoute
  '/api/v1/auth/passkey/available': typeof ApiV1AuthPasskeyAvailableRoute
  '/api/v1/auth/totp/$action': typeof ApiV1AuthTotpActionRoute
  '/api/v1/auth/passkey/$flow/$action': typeof ApiV1AuthPasskeyFlowActionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/posts/$slug'
    | '/api/v1/auth/forgot-password'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/me'
    | '/api/v1/auth/password'
    | '/api/v1/auth/refresh'
    | '/api/v1/auth/reset-password'
    | '/api/v1/comments/$id'
    | '/api/v1/comments/batch'
    | '/api/v1/passkeys/$id'
    | '/api/v1/profile/send-code'
    | '/api/v1/visitor/weather'
    | '/api/v1/passkeys/'
    | '/api/v1/profile/'
    | '/api/v1/auth/passkey/available'
    | '/api/v1/auth/totp/$action'
    | '/api/v1/auth/passkey/$flow/$action'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/posts/$slug'
    | '/api/v1/auth/forgot-password'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/me'
    | '/api/v1/auth/password'
    | '/api/v1/auth/refresh'
    | '/api/v1/auth/reset-password'
    | '/api/v1/comments/$id'
    | '/api/v1/comments/batch'
    | '/api/v1/passkeys/$id'
    | '/api/v1/profile/send-code'
    | '/api/v1/visitor/weather'
    | '/api/v1/passkeys'
    | '/api/v1/profile'
    | '/api/v1/auth/passkey/available'
    | '/api/v1/auth/totp/$action'
    | '/api/v1/auth/passkey/$flow/$action'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/posts/$slug'
    | '/api/v1/auth/forgot-password'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/me'
    | '/api/v1/auth/password'
    | '/api/v1/auth/refresh'
    | '/api/v1/auth/reset-password'
    | '/api/v1/comments/$id'
    | '/api/v1/comments/batch'
    | '/api/v1/passkeys/$id'
    | '/api/v1/profile/send-code'
    | '/api/v1/visitor/weather'
    | '/api/v1/passkeys/'
    | '/api/v1/profile/'
    | '/api/v1/auth/passkey/available'
    | '/api/v1/auth/totp/$action'
    | '/api/v1/auth/passkey/$flow/$action'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  PostsSlugRoute: typeof PostsSlugRoute
  ApiV1AuthForgotPasswordRoute: typeof ApiV1AuthForgotPasswordRoute
  ApiV1AuthLoginRoute: typeof ApiV1AuthLoginRoute
  ApiV1AuthLogoutRoute: typeof ApiV1AuthLogoutRoute
  ApiV1AuthMeRoute: typeof ApiV1AuthMeRoute
  ApiV1AuthPasswordRoute: typeof ApiV1AuthPasswordRoute
  ApiV1AuthRefreshRoute: typeof ApiV1AuthRefreshRoute
  ApiV1AuthResetPasswordRoute: typeof ApiV1AuthResetPasswordRoute
  ApiV1CommentsIdRoute: typeof ApiV1CommentsIdRoute
  ApiV1CommentsBatchRoute: typeof ApiV1CommentsBatchRoute
  ApiV1PasskeysIdRoute: typeof ApiV1PasskeysIdRoute
  ApiV1ProfileSendCodeRoute: typeof ApiV1ProfileSendCodeRoute
  ApiV1VisitorWeatherRoute: typeof ApiV1VisitorWeatherRoute
  ApiV1PasskeysIndexRoute: typeof ApiV1PasskeysIndexRoute
  ApiV1ProfileIndexRoute: typeof ApiV1ProfileIndexRoute
  ApiV1AuthPasskeyAvailableRoute: typeof ApiV1AuthPasskeyAvailableRoute
  ApiV1AuthTotpActionRoute: typeof ApiV1AuthTotpActionRoute
  ApiV1AuthPasskeyFlowActionRoute: typeof ApiV1AuthPasskeyFlowActionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/profile/': {
      id: '/api/v1/profile/'
      path: '/api/v1/profile'
      fullPath: '/api/v1/profile/'
      preLoaderRoute: typeof ApiV1ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/passkeys/': {
      id: '/api/v1/passkeys/'
      path: '/api/v1/passkeys'
      fullPath: '/api/v1/passkeys/'
      preLoaderRoute: typeof ApiV1PasskeysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/visitor/weather': {
      id: '/api/v1/visitor/weather'
      path: '/api/v1/visitor/weather'
      fullPath: '/api/v1/visitor/weather'
      preLoaderRoute: typeof ApiV1VisitorWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/profile/send-code': {
      id: '/api/v1/profile/send-code'
      path: '/api/v1/profile/send-code'
      fullPath: '/api/v1/profile/send-code'
      preLoaderRoute: typeof ApiV1ProfileSendCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/passkeys/$id': {
      id: '/api/v1/passkeys/$id'
      path: '/api/v1/passkeys/$id'
      fullPath: '/api/v1/passkeys/$id'
      preLoaderRoute: typeof ApiV1PasskeysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/comments/batch': {
      id: '/api/v1/comments/batch'
      path: '/api/v1/comments/batch'
      fullPath: '/api/v1/comments/batch'
      preLoaderRoute: typeof ApiV1CommentsBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/comments/$id': {
      id: '/api/v1/comments/$id'
      path: '/api/v1/comments/$id'
      fullPath: '/api/v1/comments/$id'
      preLoaderRoute: typeof ApiV1CommentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/reset-password': {
      id: '/api/v1/auth/reset-password'
      path: '/api/v1/auth/reset-password'
      fullPath: '/api/v1/auth/reset-password'
      preLoaderRoute: typeof ApiV1AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/refresh': {
      id: '/api/v1/auth/refresh'
      path: '/api/v1/auth/refresh'
      fullPath: '/api/v1/auth/refresh'
      preLoaderRoute: typeof ApiV1AuthRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/password': {
      id: '/api/v1/auth/password'
      path: '/api/v1/auth/password'
      fullPath: '/api/v1/auth/password'
      preLoaderRoute: typeof ApiV1AuthPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/me': {
      id: '/api/v1/auth/me'
      path: '/api/v1/auth/me'
      fullPath: '/api/v1/auth/me'
      preLoaderRoute: typeof ApiV1AuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/logout': {
      id: '/api/v1/auth/logout'
      path: '/api/v1/auth/logout'
      fullPath: '/api/v1/auth/logout'
      preLoaderRoute: typeof ApiV1AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/login': {
      id: '/api/v1/auth/login'
      path: '/api/v1/auth/login'
      fullPath: '/api/v1/auth/login'
      preLoaderRoute: typeof ApiV1AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/forgot-password': {
      id: '/api/v1/auth/forgot-password'
      path: '/api/v1/auth/forgot-password'
      fullPath: '/api/v1/auth/forgot-password'
      preLoaderRoute: typeof ApiV1AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/totp/$action': {
      id: '/api/v1/auth/totp/$action'
      path: '/api/v1/auth/totp/$action'
      fullPath: '/api/v1/auth/totp/$action'
      preLoaderRoute: typeof ApiV1AuthTotpActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/passkey/available': {
      id: '/api/v1/auth/passkey/available'
      path: '/api/v1/auth/passkey/available'
      fullPath: '/api/v1/auth/passkey/available'
      preLoaderRoute: typeof ApiV1AuthPasskeyAvailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/passkey/$flow/$action': {
      id: '/api/v1/auth/passkey/$flow/$action'
      path: '/api/v1/auth/passkey/$flow/$action'
      fullPath: '/api/v1/auth/passkey/$flow/$action'
      preLoaderRoute: typeof ApiV1AuthPasskeyFlowActionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  PostsSlugRoute: PostsSlugRoute,
  ApiV1AuthForgotPasswordRoute: ApiV1AuthForgotPasswordRoute,
  ApiV1AuthLoginRoute: ApiV1AuthLoginRoute,
  ApiV1AuthLogoutRoute: ApiV1AuthLogoutRoute,
  ApiV1AuthMeRoute: ApiV1AuthMeRoute,
  ApiV1AuthPasswordRoute: ApiV1AuthPasswordRoute,
  ApiV1AuthRefreshRoute: ApiV1AuthRefreshRoute,
  ApiV1AuthResetPasswordRoute: ApiV1AuthResetPasswordRoute,
  ApiV1CommentsIdRoute: ApiV1CommentsIdRoute,
  ApiV1CommentsBatchRoute: ApiV1CommentsBatchRoute,
  ApiV1PasskeysIdRoute: ApiV1PasskeysIdRoute,
  ApiV1ProfileSendCodeRoute: ApiV1ProfileSendCodeRoute,
  ApiV1VisitorWeatherRoute: ApiV1VisitorWeatherRoute,
  ApiV1PasskeysIndexRoute: ApiV1PasskeysIndexRoute,
  ApiV1ProfileIndexRoute: ApiV1ProfileIndexRoute,
  ApiV1AuthPasskeyAvailableRoute: ApiV1AuthPasskeyAvailableRoute,
  ApiV1AuthTotpActionRoute: ApiV1AuthTotpActionRoute,
  ApiV1AuthPasskeyFlowActionRoute: ApiV1AuthPasskeyFlowActionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
