/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstallRouteImport } from './routes/install'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsSlugRouteImport } from './routes/posts/$slug'
import { Route as AdminSplatRouteImport } from './routes/admin/$'
import { Route as ApiV1TagsRouteImport } from './routes/api/v1/tags'
import { Route as ApiV1PostsRouteImport } from './routes/api/v1/posts'
import { Route as ApiV1OwnerRouteImport } from './routes/api/v1/owner'
import { Route as ApiV1OptionsRouteImport } from './routes/api/v1/options'
import { Route as ApiV1FootprintsRouteImport } from './routes/api/v1/footprints'
import { Route as ApiV1CodingRouteImport } from './routes/api/v1/coding'
import { Route as ApiV1CategoriesRouteImport } from './routes/api/v1/categories'
import { Route as ApiV1ResourceRouteImport } from './routes/api/v1/$resource'
import { Route as ApiV1ProfileIndexRouteImport } from './routes/api/v1/profile/index'
import { Route as ApiV1PasskeysIndexRouteImport } from './routes/api/v1/passkeys/index'
import { Route as ApiV1NotificationsIndexRouteImport } from './routes/api/v1/notifications/index'
import { Route as ApiV1MomentsIndexRouteImport } from './routes/api/v1/moments/index'
import { Route as ApiV1MediaIndexRouteImport } from './routes/api/v1/media/index'
import { Route as ApiV1CommentsIndexRouteImport } from './routes/api/v1/comments/index'
import { Route as ApiV1AnalyticsIndexRouteImport } from './routes/api/v1/analytics/index'
import { Route as ApiV1VisitorWeatherRouteImport } from './routes/api/v1/visitor/weather'
import { Route as ApiV1TagsIdRouteImport } from './routes/api/v1/tags/$id'
import { Route as ApiV1SystemStatusRouteImport } from './routes/api/v1/system/status'
import { Route as ApiV1SecurityActionRouteImport } from './routes/api/v1/security/$action'
import { Route as ApiV1ProfileSendCodeRouteImport } from './routes/api/v1/profile/send-code'
import { Route as ApiV1PostsIdRouteImport } from './routes/api/v1/posts/$id'
import { Route as ApiV1PlaylistsImportRouteImport } from './routes/api/v1/playlists/import'
import { Route as ApiV1PasskeysIdRouteImport } from './routes/api/v1/passkeys/$id'
import { Route as ApiV1NotificationsUnreadCountRouteImport } from './routes/api/v1/notifications/unread-count'
import { Route as ApiV1NotificationsStreamRouteImport } from './routes/api/v1/notifications/stream'
import { Route as ApiV1NotificationsReadAllRouteImport } from './routes/api/v1/notifications/read-all'
import { Route as ApiV1NotificationsIdRouteImport } from './routes/api/v1/notifications/$id'
import { Route as ApiV1MomentsRecentTagsRouteImport } from './routes/api/v1/moments/recent-tags'
import { Route as ApiV1MomentsIdRouteImport } from './routes/api/v1/moments/$id'
import { Route as ApiV1MediaUploadBrandingRouteImport } from './routes/api/v1/media/upload-branding'
import { Route as ApiV1MediaUploadRouteImport } from './routes/api/v1/media/upload'
import { Route as ApiV1MediaTestConnectionRouteImport } from './routes/api/v1/media/test-connection'
import { Route as ApiV1MediaStatsRouteImport } from './routes/api/v1/media/stats'
import { Route as ApiV1MediaExifRouteImport } from './routes/api/v1/media/exif'
import { Route as ApiV1MediaDownloadUrlRouteImport } from './routes/api/v1/media/download-url'
import { Route as ApiV1MediaIdRouteImport } from './routes/api/v1/media/$id'
import { Route as ApiV1LinksApplyRouteImport } from './routes/api/v1/links/apply'
import { Route as ApiV1CommentsPendingCountRouteImport } from './routes/api/v1/comments/pending-count'
import { Route as ApiV1CommentsBatchRouteImport } from './routes/api/v1/comments/batch'
import { Route as ApiV1CommentsIdRouteImport } from './routes/api/v1/comments/$id'
import { Route as ApiV1CategoriesIdRouteImport } from './routes/api/v1/categories/$id'
import { Route as ApiV1CaptchaImageRouteImport } from './routes/api/v1/captcha/image'
import { Route as ApiV1CaptchaChallengeRouteImport } from './routes/api/v1/captcha/challenge'
import { Route as ApiV1BackupActionRouteImport } from './routes/api/v1/backup/$action'
import { Route as ApiV1AuthResetPasswordRouteImport } from './routes/api/v1/auth/reset-password'
import { Route as ApiV1AuthRefreshRouteImport } from './routes/api/v1/auth/refresh'
import { Route as ApiV1AuthPasswordRouteImport } from './routes/api/v1/auth/password'
import { Route as ApiV1AuthMeRouteImport } from './routes/api/v1/auth/me'
import { Route as ApiV1AuthLogoutRouteImport } from './routes/api/v1/auth/logout'
import { Route as ApiV1AuthLoginRouteImport } from './routes/api/v1/auth/login'
import { Route as ApiV1AuthForgotPasswordRouteImport } from './routes/api/v1/auth/forgot-password'
import { Route as ApiV1ArchiveStatsRouteImport } from './routes/api/v1/archive/stats'
import { Route as ApiV1AnalyticsActionRouteImport } from './routes/api/v1/analytics/$action'
import { Route as ApiV1AdminStatsRouteImport } from './routes/api/v1/admin/stats'
import { Route as ApiV1ResourceIdRouteImport } from './routes/api/v1/$resource/$id'
import { Route as ApiV1PublicAlbumsIndexRouteImport } from './routes/api/v1/public/albums/index'
import { Route as ApiV1PublicAlbumsIdRouteImport } from './routes/api/v1/public/albums/$id'
import { Route as ApiV1PostsSlugSlugRouteImport } from './routes/api/v1/posts/slug/$slug'
import { Route as ApiV1PostsByDisplayIdDisplayIdRouteImport } from './routes/api/v1/posts/by-display-id/$displayId'
import { Route as ApiV1PostsIdNavigationRouteImport } from './routes/api/v1/posts/$id/navigation'
import { Route as ApiV1PostsIdEpisodesRouteImport } from './routes/api/v1/posts/$id/episodes'
import { Route as ApiV1PostsIdCommentsRouteImport } from './routes/api/v1/posts/$id/comments'
import { Route as ApiV1PlaylistsIdSongsRouteImport } from './routes/api/v1/playlists/$id/songs'
import { Route as ApiV1NotificationsIdReadRouteImport } from './routes/api/v1/notifications/$id/read'
import { Route as ApiV1CommentsIdReplyRouteImport } from './routes/api/v1/comments/$id/reply'
import { Route as ApiV1CommentsIdEditRouteImport } from './routes/api/v1/comments/$id/edit'
import { Route as ApiV1CommentsIdApproveRouteImport } from './routes/api/v1/comments/$id/approve'
import { Route as ApiV1BackupDownloadFilenameRouteImport } from './routes/api/v1/backup/download/$filename'
import { Route as ApiV1AuthTotpActionRouteImport } from './routes/api/v1/auth/totp/$action'
import { Route as ApiV1AuthPasskeyAvailableRouteImport } from './routes/api/v1/auth/passkey/available'
import { Route as ApiV1AlbumsIdPhotosRouteImport } from './routes/api/v1/albums/$id/photos'
import { Route as ApiV1AuthPasskeyFlowActionRouteImport } from './routes/api/v1/auth/passkey/$flow/$action'
import { Route as ApiV1AlbumsIdPhotosMediaIdRouteImport } from './routes/api/v1/albums/$id/photos/$mediaId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TagsRoute = ApiV1TagsRouteImport.update({
  id: '/api/v1/tags',
  path: '/api/v1/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PostsRoute = ApiV1PostsRouteImport.update({
  id: '/api/v1/posts',
  path: '/api/v1/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OwnerRoute = ApiV1OwnerRouteImport.update({
  id: '/api/v1/owner',
  path: '/api/v1/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OptionsRoute = ApiV1OptionsRouteImport.update({
  id: '/api/v1/options',
  path: '/api/v1/options',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1FootprintsRoute = ApiV1FootprintsRouteImport.update({
  id: '/api/v1/footprints',
  path: '/api/v1/footprints',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CodingRoute = ApiV1CodingRouteImport.update({
  id: '/api/v1/coding',
  path: '/api/v1/coding',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CategoriesRoute = ApiV1CategoriesRouteImport.update({
  id: '/api/v1/categories',
  path: '/api/v1/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ResourceRoute = ApiV1ResourceRouteImport.update({
  id: '/api/v1/$resource',
  path: '/api/v1/$resource',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProfileIndexRoute = ApiV1ProfileIndexRouteImport.update({
  id: '/api/v1/profile/',
  path: '/api/v1/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PasskeysIndexRoute = ApiV1PasskeysIndexRouteImport.update({
  id: '/api/v1/passkeys/',
  path: '/api/v1/passkeys/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1NotificationsIndexRoute = ApiV1NotificationsIndexRouteImport.update({
  id: '/api/v1/notifications/',
  path: '/api/v1/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MomentsIndexRoute = ApiV1MomentsIndexRouteImport.update({
  id: '/api/v1/moments/',
  path: '/api/v1/moments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MediaIndexRoute = ApiV1MediaIndexRouteImport.update({
  id: '/api/v1/media/',
  path: '/api/v1/media/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CommentsIndexRoute = ApiV1CommentsIndexRouteImport.update({
  id: '/api/v1/comments/',
  path: '/api/v1/comments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AnalyticsIndexRoute = ApiV1AnalyticsIndexRouteImport.update({
  id: '/api/v1/analytics/',
  path: '/api/v1/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1VisitorWeatherRoute = ApiV1VisitorWeatherRouteImport.update({
  id: '/api/v1/visitor/weather',
  path: '/api/v1/visitor/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TagsIdRoute = ApiV1TagsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1TagsRoute,
} as any)
const ApiV1SystemStatusRoute = ApiV1SystemStatusRouteImport.update({
  id: '/api/v1/system/status',
  path: '/api/v1/system/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SecurityActionRoute = ApiV1SecurityActionRouteImport.update({
  id: '/api/v1/security/$action',
  path: '/api/v1/security/$action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProfileSendCodeRoute = ApiV1ProfileSendCodeRouteImport.update({
  id: '/api/v1/profile/send-code',
  path: '/api/v1/profile/send-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PostsIdRoute = ApiV1PostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1PostsRoute,
} as any)
const ApiV1PlaylistsImportRoute = ApiV1PlaylistsImportRouteImport.update({
  id: '/api/v1/playlists/import',
  path: '/api/v1/playlists/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PasskeysIdRoute = ApiV1PasskeysIdRouteImport.update({
  id: '/api/v1/passkeys/$id',
  path: '/api/v1/passkeys/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1NotificationsUnreadCountRoute =
  ApiV1NotificationsUnreadCountRouteImport.update({
    id: '/api/v1/notifications/unread-count',
    path: '/api/v1/notifications/unread-count',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1NotificationsStreamRoute =
  ApiV1NotificationsStreamRouteImport.update({
    id: '/api/v1/notifications/stream',
    path: '/api/v1/notifications/stream',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1NotificationsReadAllRoute =
  ApiV1NotificationsReadAllRouteImport.update({
    id: '/api/v1/notifications/read-all',
    path: '/api/v1/notifications/read-all',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1NotificationsIdRoute = ApiV1NotificationsIdRouteImport.update({
  id: '/api/v1/notifications/$id',
  path: '/api/v1/notifications/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MomentsRecentTagsRoute = ApiV1MomentsRecentTagsRouteImport.update({
  id: '/api/v1/moments/recent-tags',
  path: '/api/v1/moments/recent-tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MomentsIdRoute = ApiV1MomentsIdRouteImport.update({
  id: '/api/v1/moments/$id',
  path: '/api/v1/moments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MediaUploadBrandingRoute =
  ApiV1MediaUploadBrandingRouteImport.update({
    id: '/api/v1/media/upload-branding',
    path: '/api/v1/media/upload-branding',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1MediaUploadRoute = ApiV1MediaUploadRouteImport.update({
  id: '/api/v1/media/upload',
  path: '/api/v1/media/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MediaTestConnectionRoute =
  ApiV1MediaTestConnectionRouteImport.update({
    id: '/api/v1/media/test-connection',
    path: '/api/v1/media/test-connection',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1MediaStatsRoute = ApiV1MediaStatsRouteImport.update({
  id: '/api/v1/media/stats',
  path: '/api/v1/media/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MediaExifRoute = ApiV1MediaExifRouteImport.update({
  id: '/api/v1/media/exif',
  path: '/api/v1/media/exif',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MediaDownloadUrlRoute = ApiV1MediaDownloadUrlRouteImport.update({
  id: '/api/v1/media/download-url',
  path: '/api/v1/media/download-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MediaIdRoute = ApiV1MediaIdRouteImport.update({
  id: '/api/v1/media/$id',
  path: '/api/v1/media/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LinksApplyRoute = ApiV1LinksApplyRouteImport.update({
  id: '/api/v1/links/apply',
  path: '/api/v1/links/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CommentsPendingCountRoute =
  ApiV1CommentsPendingCountRouteImport.update({
    id: '/api/v1/comments/pending-count',
    path: '/api/v1/comments/pending-count',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1CommentsBatchRoute = ApiV1CommentsBatchRouteImport.update({
  id: '/api/v1/comments/batch',
  path: '/api/v1/comments/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CommentsIdRoute = ApiV1CommentsIdRouteImport.update({
  id: '/api/v1/comments/$id',
  path: '/api/v1/comments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CategoriesIdRoute = ApiV1CategoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1CategoriesRoute,
} as any)
const ApiV1CaptchaImageRoute = ApiV1CaptchaImageRouteImport.update({
  id: '/api/v1/captcha/image',
  path: '/api/v1/captcha/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CaptchaChallengeRoute = ApiV1CaptchaChallengeRouteImport.update({
  id: '/api/v1/captcha/challenge',
  path: '/api/v1/captcha/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BackupActionRoute = ApiV1BackupActionRouteImport.update({
  id: '/api/v1/backup/$action',
  path: '/api/v1/backup/$action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthResetPasswordRoute = ApiV1AuthResetPasswordRouteImport.update({
  id: '/api/v1/auth/reset-password',
  path: '/api/v1/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthRefreshRoute = ApiV1AuthRefreshRouteImport.update({
  id: '/api/v1/auth/refresh',
  path: '/api/v1/auth/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthPasswordRoute = ApiV1AuthPasswordRouteImport.update({
  id: '/api/v1/auth/password',
  path: '/api/v1/auth/password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthMeRoute = ApiV1AuthMeRouteImport.update({
  id: '/api/v1/auth/me',
  path: '/api/v1/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthLogoutRoute = ApiV1AuthLogoutRouteImport.update({
  id: '/api/v1/auth/logout',
  path: '/api/v1/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthLoginRoute = ApiV1AuthLoginRouteImport.update({
  id: '/api/v1/auth/login',
  path: '/api/v1/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthForgotPasswordRoute = ApiV1AuthForgotPasswordRouteImport.update({
  id: '/api/v1/auth/forgot-password',
  path: '/api/v1/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ArchiveStatsRoute = ApiV1ArchiveStatsRouteImport.update({
  id: '/api/v1/archive/stats',
  path: '/api/v1/archive/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AnalyticsActionRoute = ApiV1AnalyticsActionRouteImport.update({
  id: '/api/v1/analytics/$action',
  path: '/api/v1/analytics/$action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AdminStatsRoute = ApiV1AdminStatsRouteImport.update({
  id: '/api/v1/admin/stats',
  path: '/api/v1/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ResourceIdRoute = ApiV1ResourceIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1ResourceRoute,
} as any)
const ApiV1PublicAlbumsIndexRoute = ApiV1PublicAlbumsIndexRouteImport.update({
  id: '/api/v1/public/albums/',
  path: '/api/v1/public/albums/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PublicAlbumsIdRoute = ApiV1PublicAlbumsIdRouteImport.update({
  id: '/api/v1/public/albums/$id',
  path: '/api/v1/public/albums/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PostsSlugSlugRoute = ApiV1PostsSlugSlugRouteImport.update({
  id: '/slug/$slug',
  path: '/slug/$slug',
  getParentRoute: () => ApiV1PostsRoute,
} as any)
const ApiV1PostsByDisplayIdDisplayIdRoute =
  ApiV1PostsByDisplayIdDisplayIdRouteImport.update({
    id: '/by-display-id/$displayId',
    path: '/by-display-id/$displayId',
    getParentRoute: () => ApiV1PostsRoute,
  } as any)
const ApiV1PostsIdNavigationRoute = ApiV1PostsIdNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => ApiV1PostsIdRoute,
} as any)
const ApiV1PostsIdEpisodesRoute = ApiV1PostsIdEpisodesRouteImport.update({
  id: '/episodes',
  path: '/episodes',
  getParentRoute: () => ApiV1PostsIdRoute,
} as any)
const ApiV1PostsIdCommentsRoute = ApiV1PostsIdCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => ApiV1PostsIdRoute,
} as any)
const ApiV1PlaylistsIdSongsRoute = ApiV1PlaylistsIdSongsRouteImport.update({
  id: '/api/v1/playlists/$id/songs',
  path: '/api/v1/playlists/$id/songs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1NotificationsIdReadRoute =
  ApiV1NotificationsIdReadRouteImport.update({
    id: '/read',
    path: '/read',
    getParentRoute: () => ApiV1NotificationsIdRoute,
  } as any)
const ApiV1CommentsIdReplyRoute = ApiV1CommentsIdReplyRouteImport.update({
  id: '/reply',
  path: '/reply',
  getParentRoute: () => ApiV1CommentsIdRoute,
} as any)
const ApiV1CommentsIdEditRoute = ApiV1CommentsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ApiV1CommentsIdRoute,
} as any)
const ApiV1CommentsIdApproveRoute = ApiV1CommentsIdApproveRouteImport.update({
  id: '/approve',
  path: '/approve',
  getParentRoute: () => ApiV1CommentsIdRoute,
} as any)
const ApiV1BackupDownloadFilenameRoute =
  ApiV1BackupDownloadFilenameRouteImport.update({
    id: '/api/v1/backup/download/$filename',
    path: '/api/v1/backup/download/$filename',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AuthTotpActionRoute = ApiV1AuthTotpActionRouteImport.update({
  id: '/api/v1/auth/totp/$action',
  path: '/api/v1/auth/totp/$action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthPasskeyAvailableRoute =
  ApiV1AuthPasskeyAvailableRouteImport.update({
    id: '/api/v1/auth/passkey/available',
    path: '/api/v1/auth/passkey/available',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AlbumsIdPhotosRoute = ApiV1AlbumsIdPhotosRouteImport.update({
  id: '/api/v1/albums/$id/photos',
  path: '/api/v1/albums/$id/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthPasskeyFlowActionRoute =
  ApiV1AuthPasskeyFlowActionRouteImport.update({
    id: '/api/v1/auth/passkey/$flow/$action',
    path: '/api/v1/auth/passkey/$flow/$action',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AlbumsIdPhotosMediaIdRoute =
  ApiV1AlbumsIdPhotosMediaIdRouteImport.update({
    id: '/$mediaId',
    path: '/$mediaId',
    getParentRoute: () => ApiV1AlbumsIdPhotosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/admin/$': typeof AdminSplatRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/api/v1/$resource': typeof ApiV1ResourceRouteWithChildren
  '/api/v1/categories': typeof ApiV1CategoriesRouteWithChildren
  '/api/v1/coding': typeof ApiV1CodingRoute
  '/api/v1/footprints': typeof ApiV1FootprintsRoute
  '/api/v1/options': typeof ApiV1OptionsRoute
  '/api/v1/owner': typeof ApiV1OwnerRoute
  '/api/v1/posts': typeof ApiV1PostsRouteWithChildren
  '/api/v1/tags': typeof ApiV1TagsRouteWithChildren
  '/api/v1/$resource/$id': typeof ApiV1ResourceIdRoute
  '/api/v1/admin/stats': typeof ApiV1AdminStatsRoute
  '/api/v1/analytics/$action': typeof ApiV1AnalyticsActionRoute
  '/api/v1/archive/stats': typeof ApiV1ArchiveStatsRoute
  '/api/v1/auth/forgot-password': typeof ApiV1AuthForgotPasswordRoute
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/me': typeof ApiV1AuthMeRoute
  '/api/v1/auth/password': typeof ApiV1AuthPasswordRoute
  '/api/v1/auth/refresh': typeof ApiV1AuthRefreshRoute
  '/api/v1/auth/reset-password': typeof ApiV1AuthResetPasswordRoute
  '/api/v1/backup/$action': typeof ApiV1BackupActionRoute
  '/api/v1/captcha/challenge': typeof ApiV1CaptchaChallengeRoute
  '/api/v1/captcha/image': typeof ApiV1CaptchaImageRoute
  '/api/v1/categories/$id': typeof ApiV1CategoriesIdRoute
  '/api/v1/comments/$id': typeof ApiV1CommentsIdRouteWithChildren
  '/api/v1/comments/batch': typeof ApiV1CommentsBatchRoute
  '/api/v1/comments/pending-count': typeof ApiV1CommentsPendingCountRoute
  '/api/v1/links/apply': typeof ApiV1LinksApplyRoute
  '/api/v1/media/$id': typeof ApiV1MediaIdRoute
  '/api/v1/media/download-url': typeof ApiV1MediaDownloadUrlRoute
  '/api/v1/media/exif': typeof ApiV1MediaExifRoute
  '/api/v1/media/stats': typeof ApiV1MediaStatsRoute
  '/api/v1/media/test-connection': typeof ApiV1MediaTestConnectionRoute
  '/api/v1/media/upload': typeof ApiV1MediaUploadRoute
  '/api/v1/media/upload-branding': typeof ApiV1MediaUploadBrandingRoute
  '/api/v1/moments/$id': typeof ApiV1MomentsIdRoute
  '/api/v1/moments/recent-tags': typeof ApiV1MomentsRecentTagsRoute
  '/api/v1/notifications/$id': typeof ApiV1NotificationsIdRouteWithChildren
  '/api/v1/notifications/read-all': typeof ApiV1NotificationsReadAllRoute
  '/api/v1/notifications/stream': typeof ApiV1NotificationsStreamRoute
  '/api/v1/notifications/unread-count': typeof ApiV1NotificationsUnreadCountRoute
  '/api/v1/passkeys/$id': typeof ApiV1PasskeysIdRoute
  '/api/v1/playlists/import': typeof ApiV1PlaylistsImportRoute
  '/api/v1/posts/$id': typeof ApiV1PostsIdRouteWithChildren
  '/api/v1/profile/send-code': typeof ApiV1ProfileSendCodeRoute
  '/api/v1/security/$action': typeof ApiV1SecurityActionRoute
  '/api/v1/system/status': typeof ApiV1SystemStatusRoute
  '/api/v1/tags/$id': typeof ApiV1TagsIdRoute
  '/api/v1/visitor/weather': typeof ApiV1VisitorWeatherRoute
  '/api/v1/analytics/': typeof ApiV1AnalyticsIndexRoute
  '/api/v1/comments/': typeof ApiV1CommentsIndexRoute
  '/api/v1/media/': typeof ApiV1MediaIndexRoute
  '/api/v1/moments/': typeof ApiV1MomentsIndexRoute
  '/api/v1/notifications/': typeof ApiV1NotificationsIndexRoute
  '/api/v1/passkeys/': typeof ApiV1PasskeysIndexRoute
  '/api/v1/profile/': typeof ApiV1ProfileIndexRoute
  '/api/v1/albums/$id/photos': typeof ApiV1AlbumsIdPhotosRouteWithChildren
  '/api/v1/auth/passkey/available': typeof ApiV1AuthPasskeyAvailableRoute
  '/api/v1/auth/totp/$action': typeof ApiV1AuthTotpActionRoute
  '/api/v1/backup/download/$filename': typeof ApiV1BackupDownloadFilenameRoute
  '/api/v1/comments/$id/approve': typeof ApiV1CommentsIdApproveRoute
  '/api/v1/comments/$id/edit': typeof ApiV1CommentsIdEditRoute
  '/api/v1/comments/$id/reply': typeof ApiV1CommentsIdReplyRoute
  '/api/v1/notifications/$id/read': typeof ApiV1NotificationsIdReadRoute
  '/api/v1/playlists/$id/songs': typeof ApiV1PlaylistsIdSongsRoute
  '/api/v1/posts/$id/comments': typeof ApiV1PostsIdCommentsRoute
  '/api/v1/posts/$id/episodes': typeof ApiV1PostsIdEpisodesRoute
  '/api/v1/posts/$id/navigation': typeof ApiV1PostsIdNavigationRoute
  '/api/v1/posts/by-display-id/$displayId': typeof ApiV1PostsByDisplayIdDisplayIdRoute
  '/api/v1/posts/slug/$slug': typeof ApiV1PostsSlugSlugRoute
  '/api/v1/public/albums/$id': typeof ApiV1PublicAlbumsIdRoute
  '/api/v1/public/albums/': typeof ApiV1PublicAlbumsIndexRoute
  '/api/v1/albums/$id/photos/$mediaId': typeof ApiV1AlbumsIdPhotosMediaIdRoute
  '/api/v1/auth/passkey/$flow/$action': typeof ApiV1AuthPasskeyFlowActionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/admin/$': typeof AdminSplatRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/api/v1/$resource': typeof ApiV1ResourceRouteWithChildren
  '/api/v1/categories': typeof ApiV1CategoriesRouteWithChildren
  '/api/v1/coding': typeof ApiV1CodingRoute
  '/api/v1/footprints': typeof ApiV1FootprintsRoute
  '/api/v1/options': typeof ApiV1OptionsRoute
  '/api/v1/owner': typeof ApiV1OwnerRoute
  '/api/v1/posts': typeof ApiV1PostsRouteWithChildren
  '/api/v1/tags': typeof ApiV1TagsRouteWithChildren
  '/api/v1/$resource/$id': typeof ApiV1ResourceIdRoute
  '/api/v1/admin/stats': typeof ApiV1AdminStatsRoute
  '/api/v1/analytics/$action': typeof ApiV1AnalyticsActionRoute
  '/api/v1/archive/stats': typeof ApiV1ArchiveStatsRoute
  '/api/v1/auth/forgot-password': typeof ApiV1AuthForgotPasswordRoute
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/me': typeof ApiV1AuthMeRoute
  '/api/v1/auth/password': typeof ApiV1AuthPasswordRoute
  '/api/v1/auth/refresh': typeof ApiV1AuthRefreshRoute
  '/api/v1/auth/reset-password': typeof ApiV1AuthResetPasswordRoute
  '/api/v1/backup/$action': typeof ApiV1BackupActionRoute
  '/api/v1/captcha/challenge': typeof ApiV1CaptchaChallengeRoute
  '/api/v1/captcha/image': typeof ApiV1CaptchaImageRoute
  '/api/v1/categories/$id': typeof ApiV1CategoriesIdRoute
  '/api/v1/comments/$id': typeof ApiV1CommentsIdRouteWithChildren
  '/api/v1/comments/batch': typeof ApiV1CommentsBatchRoute
  '/api/v1/comments/pending-count': typeof ApiV1CommentsPendingCountRoute
  '/api/v1/links/apply': typeof ApiV1LinksApplyRoute
  '/api/v1/media/$id': typeof ApiV1MediaIdRoute
  '/api/v1/media/download-url': typeof ApiV1MediaDownloadUrlRoute
  '/api/v1/media/exif': typeof ApiV1MediaExifRoute
  '/api/v1/media/stats': typeof ApiV1MediaStatsRoute
  '/api/v1/media/test-connection': typeof ApiV1MediaTestConnectionRoute
  '/api/v1/media/upload': typeof ApiV1MediaUploadRoute
  '/api/v1/media/upload-branding': typeof ApiV1MediaUploadBrandingRoute
  '/api/v1/moments/$id': typeof ApiV1MomentsIdRoute
  '/api/v1/moments/recent-tags': typeof ApiV1MomentsRecentTagsRoute
  '/api/v1/notifications/$id': typeof ApiV1NotificationsIdRouteWithChildren
  '/api/v1/notifications/read-all': typeof ApiV1NotificationsReadAllRoute
  '/api/v1/notifications/stream': typeof ApiV1NotificationsStreamRoute
  '/api/v1/notifications/unread-count': typeof ApiV1NotificationsUnreadCountRoute
  '/api/v1/passkeys/$id': typeof ApiV1PasskeysIdRoute
  '/api/v1/playlists/import': typeof ApiV1PlaylistsImportRoute
  '/api/v1/posts/$id': typeof ApiV1PostsIdRouteWithChildren
  '/api/v1/profile/send-code': typeof ApiV1ProfileSendCodeRoute
  '/api/v1/security/$action': typeof ApiV1SecurityActionRoute
  '/api/v1/system/status': typeof ApiV1SystemStatusRoute
  '/api/v1/tags/$id': typeof ApiV1TagsIdRoute
  '/api/v1/visitor/weather': typeof ApiV1VisitorWeatherRoute
  '/api/v1/analytics': typeof ApiV1AnalyticsIndexRoute
  '/api/v1/comments': typeof ApiV1CommentsIndexRoute
  '/api/v1/media': typeof ApiV1MediaIndexRoute
  '/api/v1/moments': typeof ApiV1MomentsIndexRoute
  '/api/v1/notifications': typeof ApiV1NotificationsIndexRoute
  '/api/v1/passkeys': typeof ApiV1PasskeysIndexRoute
  '/api/v1/profile': typeof ApiV1ProfileIndexRoute
  '/api/v1/albums/$id/photos': typeof ApiV1AlbumsIdPhotosRouteWithChildren
  '/api/v1/auth/passkey/available': typeof ApiV1AuthPasskeyAvailableRoute
  '/api/v1/auth/totp/$action': typeof ApiV1AuthTotpActionRoute
  '/api/v1/backup/download/$filename': typeof ApiV1BackupDownloadFilenameRoute
  '/api/v1/comments/$id/approve': typeof ApiV1CommentsIdApproveRoute
  '/api/v1/comments/$id/edit': typeof ApiV1CommentsIdEditRoute
  '/api/v1/comments/$id/reply': typeof ApiV1CommentsIdReplyRoute
  '/api/v1/notifications/$id/read': typeof ApiV1NotificationsIdReadRoute
  '/api/v1/playlists/$id/songs': typeof ApiV1PlaylistsIdSongsRoute
  '/api/v1/posts/$id/comments': typeof ApiV1PostsIdCommentsRoute
  '/api/v1/posts/$id/episodes': typeof ApiV1PostsIdEpisodesRoute
  '/api/v1/posts/$id/navigation': typeof ApiV1PostsIdNavigationRoute
  '/api/v1/posts/by-display-id/$displayId': typeof ApiV1PostsByDisplayIdDisplayIdRoute
  '/api/v1/posts/slug/$slug': typeof ApiV1PostsSlugSlugRoute
  '/api/v1/public/albums/$id': typeof ApiV1PublicAlbumsIdRoute
  '/api/v1/public/albums': typeof ApiV1PublicAlbumsIndexRoute
  '/api/v1/albums/$id/photos/$mediaId': typeof ApiV1AlbumsIdPhotosMediaIdRoute
  '/api/v1/auth/passkey/$flow/$action': typeof ApiV1AuthPasskeyFlowActionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/admin/$': typeof AdminSplatRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/api/v1/$resource': typeof ApiV1ResourceRouteWithChildren
  '/api/v1/categories': typeof ApiV1CategoriesRouteWithChildren
  '/api/v1/coding': typeof ApiV1CodingRoute
  '/api/v1/footprints': typeof ApiV1FootprintsRoute
  '/api/v1/options': typeof ApiV1OptionsRoute
  '/api/v1/owner': typeof ApiV1OwnerRoute
  '/api/v1/posts': typeof ApiV1PostsRouteWithChildren
  '/api/v1/tags': typeof ApiV1TagsRouteWithChildren
  '/api/v1/$resource/$id': typeof ApiV1ResourceIdRoute
  '/api/v1/admin/stats': typeof ApiV1AdminStatsRoute
  '/api/v1/analytics/$action': typeof ApiV1AnalyticsActionRoute
  '/api/v1/archive/stats': typeof ApiV1ArchiveStatsRoute
  '/api/v1/auth/forgot-password': typeof ApiV1AuthForgotPasswordRoute
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/me': typeof ApiV1AuthMeRoute
  '/api/v1/auth/password': typeof ApiV1AuthPasswordRoute
  '/api/v1/auth/refresh': typeof ApiV1AuthRefreshRoute
  '/api/v1/auth/reset-password': typeof ApiV1AuthResetPasswordRoute
  '/api/v1/backup/$action': typeof ApiV1BackupActionRoute
  '/api/v1/captcha/challenge': typeof ApiV1CaptchaChallengeRoute
  '/api/v1/captcha/image': typeof ApiV1CaptchaImageRoute
  '/api/v1/categories/$id': typeof ApiV1CategoriesIdRoute
  '/api/v1/comments/$id': typeof ApiV1CommentsIdRouteWithChildren
  '/api/v1/comments/batch': typeof ApiV1CommentsBatchRoute
  '/api/v1/comments/pending-count': typeof ApiV1CommentsPendingCountRoute
  '/api/v1/links/apply': typeof ApiV1LinksApplyRoute
  '/api/v1/media/$id': typeof ApiV1MediaIdRoute
  '/api/v1/media/download-url': typeof ApiV1MediaDownloadUrlRoute
  '/api/v1/media/exif': typeof ApiV1MediaExifRoute
  '/api/v1/media/stats': typeof ApiV1MediaStatsRoute
  '/api/v1/media/test-connection': typeof ApiV1MediaTestConnectionRoute
  '/api/v1/media/upload': typeof ApiV1MediaUploadRoute
  '/api/v1/media/upload-branding': typeof ApiV1MediaUploadBrandingRoute
  '/api/v1/moments/$id': typeof ApiV1MomentsIdRoute
  '/api/v1/moments/recent-tags': typeof ApiV1MomentsRecentTagsRoute
  '/api/v1/notifications/$id': typeof ApiV1NotificationsIdRouteWithChildren
  '/api/v1/notifications/read-all': typeof ApiV1NotificationsReadAllRoute
  '/api/v1/notifications/stream': typeof ApiV1NotificationsStreamRoute
  '/api/v1/notifications/unread-count': typeof ApiV1NotificationsUnreadCountRoute
  '/api/v1/passkeys/$id': typeof ApiV1PasskeysIdRoute
  '/api/v1/playlists/import': typeof ApiV1PlaylistsImportRoute
  '/api/v1/posts/$id': typeof ApiV1PostsIdRouteWithChildren
  '/api/v1/profile/send-code': typeof ApiV1ProfileSendCodeRoute
  '/api/v1/security/$action': typeof ApiV1SecurityActionRoute
  '/api/v1/system/status': typeof ApiV1SystemStatusRoute
  '/api/v1/tags/$id': typeof ApiV1TagsIdRoute
  '/api/v1/visitor/weather': typeof ApiV1VisitorWeatherRoute
  '/api/v1/analytics/': typeof ApiV1AnalyticsIndexRoute
  '/api/v1/comments/': typeof ApiV1CommentsIndexRoute
  '/api/v1/media/': typeof ApiV1MediaIndexRoute
  '/api/v1/moments/': typeof ApiV1MomentsIndexRoute
  '/api/v1/notifications/': typeof ApiV1NotificationsIndexRoute
  '/api/v1/passkeys/': typeof ApiV1PasskeysIndexRoute
  '/api/v1/profile/': typeof ApiV1ProfileIndexRoute
  '/api/v1/albums/$id/photos': typeof ApiV1AlbumsIdPhotosRouteWithChildren
  '/api/v1/auth/passkey/available': typeof ApiV1AuthPasskeyAvailableRoute
  '/api/v1/auth/totp/$action': typeof ApiV1AuthTotpActionRoute
  '/api/v1/backup/download/$filename': typeof ApiV1BackupDownloadFilenameRoute
  '/api/v1/comments/$id/approve': typeof ApiV1CommentsIdApproveRoute
  '/api/v1/comments/$id/edit': typeof ApiV1CommentsIdEditRoute
  '/api/v1/comments/$id/reply': typeof ApiV1CommentsIdReplyRoute
  '/api/v1/notifications/$id/read': typeof ApiV1NotificationsIdReadRoute
  '/api/v1/playlists/$id/songs': typeof ApiV1PlaylistsIdSongsRoute
  '/api/v1/posts/$id/comments': typeof ApiV1PostsIdCommentsRoute
  '/api/v1/posts/$id/episodes': typeof ApiV1PostsIdEpisodesRoute
  '/api/v1/posts/$id/navigation': typeof ApiV1PostsIdNavigationRoute
  '/api/v1/posts/by-display-id/$displayId': typeof ApiV1PostsByDisplayIdDisplayIdRoute
  '/api/v1/posts/slug/$slug': typeof ApiV1PostsSlugSlugRoute
  '/api/v1/public/albums/$id': typeof ApiV1PublicAlbumsIdRoute
  '/api/v1/public/albums/': typeof ApiV1PublicAlbumsIndexRoute
  '/api/v1/albums/$id/photos/$mediaId': typeof ApiV1AlbumsIdPhotosMediaIdRoute
  '/api/v1/auth/passkey/$flow/$action': typeof ApiV1AuthPasskeyFlowActionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/install'
    | '/login'
    | '/admin/$'
    | '/posts/$slug'
    | '/api/v1/$resource'
    | '/api/v1/categories'
    | '/api/v1/coding'
    | '/api/v1/footprints'
    | '/api/v1/options'
    | '/api/v1/owner'
    | '/api/v1/posts'
    | '/api/v1/tags'
    | '/api/v1/$resource/$id'
    | '/api/v1/admin/stats'
    | '/api/v1/analytics/$action'
    | '/api/v1/archive/stats'
    | '/api/v1/auth/forgot-password'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/me'
    | '/api/v1/auth/password'
    | '/api/v1/auth/refresh'
    | '/api/v1/auth/reset-password'
    | '/api/v1/backup/$action'
    | '/api/v1/captcha/challenge'
    | '/api/v1/captcha/image'
    | '/api/v1/categories/$id'
    | '/api/v1/comments/$id'
    | '/api/v1/comments/batch'
    | '/api/v1/comments/pending-count'
    | '/api/v1/links/apply'
    | '/api/v1/media/$id'
    | '/api/v1/media/download-url'
    | '/api/v1/media/exif'
    | '/api/v1/media/stats'
    | '/api/v1/media/test-connection'
    | '/api/v1/media/upload'
    | '/api/v1/media/upload-branding'
    | '/api/v1/moments/$id'
    | '/api/v1/moments/recent-tags'
    | '/api/v1/notifications/$id'
    | '/api/v1/notifications/read-all'
    | '/api/v1/notifications/stream'
    | '/api/v1/notifications/unread-count'
    | '/api/v1/passkeys/$id'
    | '/api/v1/playlists/import'
    | '/api/v1/posts/$id'
    | '/api/v1/profile/send-code'
    | '/api/v1/security/$action'
    | '/api/v1/system/status'
    | '/api/v1/tags/$id'
    | '/api/v1/visitor/weather'
    | '/api/v1/analytics/'
    | '/api/v1/comments/'
    | '/api/v1/media/'
    | '/api/v1/moments/'
    | '/api/v1/notifications/'
    | '/api/v1/passkeys/'
    | '/api/v1/profile/'
    | '/api/v1/albums/$id/photos'
    | '/api/v1/auth/passkey/available'
    | '/api/v1/auth/totp/$action'
    | '/api/v1/backup/download/$filename'
    | '/api/v1/comments/$id/approve'
    | '/api/v1/comments/$id/edit'
    | '/api/v1/comments/$id/reply'
    | '/api/v1/notifications/$id/read'
    | '/api/v1/playlists/$id/songs'
    | '/api/v1/posts/$id/comments'
    | '/api/v1/posts/$id/episodes'
    | '/api/v1/posts/$id/navigation'
    | '/api/v1/posts/by-display-id/$displayId'
    | '/api/v1/posts/slug/$slug'
    | '/api/v1/public/albums/$id'
    | '/api/v1/public/albums/'
    | '/api/v1/albums/$id/photos/$mediaId'
    | '/api/v1/auth/passkey/$flow/$action'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/install'
    | '/login'
    | '/admin/$'
    | '/posts/$slug'
    | '/api/v1/$resource'
    | '/api/v1/categories'
    | '/api/v1/coding'
    | '/api/v1/footprints'
    | '/api/v1/options'
    | '/api/v1/owner'
    | '/api/v1/posts'
    | '/api/v1/tags'
    | '/api/v1/$resource/$id'
    | '/api/v1/admin/stats'
    | '/api/v1/analytics/$action'
    | '/api/v1/archive/stats'
    | '/api/v1/auth/forgot-password'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/me'
    | '/api/v1/auth/password'
    | '/api/v1/auth/refresh'
    | '/api/v1/auth/reset-password'
    | '/api/v1/backup/$action'
    | '/api/v1/captcha/challenge'
    | '/api/v1/captcha/image'
    | '/api/v1/categories/$id'
    | '/api/v1/comments/$id'
    | '/api/v1/comments/batch'
    | '/api/v1/comments/pending-count'
    | '/api/v1/links/apply'
    | '/api/v1/media/$id'
    | '/api/v1/media/download-url'
    | '/api/v1/media/exif'
    | '/api/v1/media/stats'
    | '/api/v1/media/test-connection'
    | '/api/v1/media/upload'
    | '/api/v1/media/upload-branding'
    | '/api/v1/moments/$id'
    | '/api/v1/moments/recent-tags'
    | '/api/v1/notifications/$id'
    | '/api/v1/notifications/read-all'
    | '/api/v1/notifications/stream'
    | '/api/v1/notifications/unread-count'
    | '/api/v1/passkeys/$id'
    | '/api/v1/playlists/import'
    | '/api/v1/posts/$id'
    | '/api/v1/profile/send-code'
    | '/api/v1/security/$action'
    | '/api/v1/system/status'
    | '/api/v1/tags/$id'
    | '/api/v1/visitor/weather'
    | '/api/v1/analytics'
    | '/api/v1/comments'
    | '/api/v1/media'
    | '/api/v1/moments'
    | '/api/v1/notifications'
    | '/api/v1/passkeys'
    | '/api/v1/profile'
    | '/api/v1/albums/$id/photos'
    | '/api/v1/auth/passkey/available'
    | '/api/v1/auth/totp/$action'
    | '/api/v1/backup/download/$filename'
    | '/api/v1/comments/$id/approve'
    | '/api/v1/comments/$id/edit'
    | '/api/v1/comments/$id/reply'
    | '/api/v1/notifications/$id/read'
    | '/api/v1/playlists/$id/songs'
    | '/api/v1/posts/$id/comments'
    | '/api/v1/posts/$id/episodes'
    | '/api/v1/posts/$id/navigation'
    | '/api/v1/posts/by-display-id/$displayId'
    | '/api/v1/posts/slug/$slug'
    | '/api/v1/public/albums/$id'
    | '/api/v1/public/albums'
    | '/api/v1/albums/$id/photos/$mediaId'
    | '/api/v1/auth/passkey/$flow/$action'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/install'
    | '/login'
    | '/admin/$'
    | '/posts/$slug'
    | '/api/v1/$resource'
    | '/api/v1/categories'
    | '/api/v1/coding'
    | '/api/v1/footprints'
    | '/api/v1/options'
    | '/api/v1/owner'
    | '/api/v1/posts'
    | '/api/v1/tags'
    | '/api/v1/$resource/$id'
    | '/api/v1/admin/stats'
    | '/api/v1/analytics/$action'
    | '/api/v1/archive/stats'
    | '/api/v1/auth/forgot-password'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/me'
    | '/api/v1/auth/password'
    | '/api/v1/auth/refresh'
    | '/api/v1/auth/reset-password'
    | '/api/v1/backup/$action'
    | '/api/v1/captcha/challenge'
    | '/api/v1/captcha/image'
    | '/api/v1/categories/$id'
    | '/api/v1/comments/$id'
    | '/api/v1/comments/batch'
    | '/api/v1/comments/pending-count'
    | '/api/v1/links/apply'
    | '/api/v1/media/$id'
    | '/api/v1/media/download-url'
    | '/api/v1/media/exif'
    | '/api/v1/media/stats'
    | '/api/v1/media/test-connection'
    | '/api/v1/media/upload'
    | '/api/v1/media/upload-branding'
    | '/api/v1/moments/$id'
    | '/api/v1/moments/recent-tags'
    | '/api/v1/notifications/$id'
    | '/api/v1/notifications/read-all'
    | '/api/v1/notifications/stream'
    | '/api/v1/notifications/unread-count'
    | '/api/v1/passkeys/$id'
    | '/api/v1/playlists/import'
    | '/api/v1/posts/$id'
    | '/api/v1/profile/send-code'
    | '/api/v1/security/$action'
    | '/api/v1/system/status'
    | '/api/v1/tags/$id'
    | '/api/v1/visitor/weather'
    | '/api/v1/analytics/'
    | '/api/v1/comments/'
    | '/api/v1/media/'
    | '/api/v1/moments/'
    | '/api/v1/notifications/'
    | '/api/v1/passkeys/'
    | '/api/v1/profile/'
    | '/api/v1/albums/$id/photos'
    | '/api/v1/auth/passkey/available'
    | '/api/v1/auth/totp/$action'
    | '/api/v1/backup/download/$filename'
    | '/api/v1/comments/$id/approve'
    | '/api/v1/comments/$id/edit'
    | '/api/v1/comments/$id/reply'
    | '/api/v1/notifications/$id/read'
    | '/api/v1/playlists/$id/songs'
    | '/api/v1/posts/$id/comments'
    | '/api/v1/posts/$id/episodes'
    | '/api/v1/posts/$id/navigation'
    | '/api/v1/posts/by-display-id/$displayId'
    | '/api/v1/posts/slug/$slug'
    | '/api/v1/public/albums/$id'
    | '/api/v1/public/albums/'
    | '/api/v1/albums/$id/photos/$mediaId'
    | '/api/v1/auth/passkey/$flow/$action'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  InstallRoute: typeof InstallRoute
  LoginRoute: typeof LoginRoute
  AdminSplatRoute: typeof AdminSplatRoute
  PostsSlugRoute: typeof PostsSlugRoute
  ApiV1ResourceRoute: typeof ApiV1ResourceRouteWithChildren
  ApiV1CategoriesRoute: typeof ApiV1CategoriesRouteWithChildren
  ApiV1CodingRoute: typeof ApiV1CodingRoute
  ApiV1FootprintsRoute: typeof ApiV1FootprintsRoute
  ApiV1OptionsRoute: typeof ApiV1OptionsRoute
  ApiV1OwnerRoute: typeof ApiV1OwnerRoute
  ApiV1PostsRoute: typeof ApiV1PostsRouteWithChildren
  ApiV1TagsRoute: typeof ApiV1TagsRouteWithChildren
  ApiV1AdminStatsRoute: typeof ApiV1AdminStatsRoute
  ApiV1AnalyticsActionRoute: typeof ApiV1AnalyticsActionRoute
  ApiV1ArchiveStatsRoute: typeof ApiV1ArchiveStatsRoute
  ApiV1AuthForgotPasswordRoute: typeof ApiV1AuthForgotPasswordRoute
  ApiV1AuthLoginRoute: typeof ApiV1AuthLoginRoute
  ApiV1AuthLogoutRoute: typeof ApiV1AuthLogoutRoute
  ApiV1AuthMeRoute: typeof ApiV1AuthMeRoute
  ApiV1AuthPasswordRoute: typeof ApiV1AuthPasswordRoute
  ApiV1AuthRefreshRoute: typeof ApiV1AuthRefreshRoute
  ApiV1AuthResetPasswordRoute: typeof ApiV1AuthResetPasswordRoute
  ApiV1BackupActionRoute: typeof ApiV1BackupActionRoute
  ApiV1CaptchaChallengeRoute: typeof ApiV1CaptchaChallengeRoute
  ApiV1CaptchaImageRoute: typeof ApiV1CaptchaImageRoute
  ApiV1CommentsIdRoute: typeof ApiV1CommentsIdRouteWithChildren
  ApiV1CommentsBatchRoute: typeof ApiV1CommentsBatchRoute
  ApiV1CommentsPendingCountRoute: typeof ApiV1CommentsPendingCountRoute
  ApiV1LinksApplyRoute: typeof ApiV1LinksApplyRoute
  ApiV1MediaIdRoute: typeof ApiV1MediaIdRoute
  ApiV1MediaDownloadUrlRoute: typeof ApiV1MediaDownloadUrlRoute
  ApiV1MediaExifRoute: typeof ApiV1MediaExifRoute
  ApiV1MediaStatsRoute: typeof ApiV1MediaStatsRoute
  ApiV1MediaTestConnectionRoute: typeof ApiV1MediaTestConnectionRoute
  ApiV1MediaUploadRoute: typeof ApiV1MediaUploadRoute
  ApiV1MediaUploadBrandingRoute: typeof ApiV1MediaUploadBrandingRoute
  ApiV1MomentsIdRoute: typeof ApiV1MomentsIdRoute
  ApiV1MomentsRecentTagsRoute: typeof ApiV1MomentsRecentTagsRoute
  ApiV1NotificationsIdRoute: typeof ApiV1NotificationsIdRouteWithChildren
  ApiV1NotificationsReadAllRoute: typeof ApiV1NotificationsReadAllRoute
  ApiV1NotificationsStreamRoute: typeof ApiV1NotificationsStreamRoute
  ApiV1NotificationsUnreadCountRoute: typeof ApiV1NotificationsUnreadCountRoute
  ApiV1PasskeysIdRoute: typeof ApiV1PasskeysIdRoute
  ApiV1PlaylistsImportRoute: typeof ApiV1PlaylistsImportRoute
  ApiV1ProfileSendCodeRoute: typeof ApiV1ProfileSendCodeRoute
  ApiV1SecurityActionRoute: typeof ApiV1SecurityActionRoute
  ApiV1SystemStatusRoute: typeof ApiV1SystemStatusRoute
  ApiV1VisitorWeatherRoute: typeof ApiV1VisitorWeatherRoute
  ApiV1AnalyticsIndexRoute: typeof ApiV1AnalyticsIndexRoute
  ApiV1CommentsIndexRoute: typeof ApiV1CommentsIndexRoute
  ApiV1MediaIndexRoute: typeof ApiV1MediaIndexRoute
  ApiV1MomentsIndexRoute: typeof ApiV1MomentsIndexRoute
  ApiV1NotificationsIndexRoute: typeof ApiV1NotificationsIndexRoute
  ApiV1PasskeysIndexRoute: typeof ApiV1PasskeysIndexRoute
  ApiV1ProfileIndexRoute: typeof ApiV1ProfileIndexRoute
  ApiV1AlbumsIdPhotosRoute: typeof ApiV1AlbumsIdPhotosRouteWithChildren
  ApiV1AuthPasskeyAvailableRoute: typeof ApiV1AuthPasskeyAvailableRoute
  ApiV1AuthTotpActionRoute: typeof ApiV1AuthTotpActionRoute
  ApiV1BackupDownloadFilenameRoute: typeof ApiV1BackupDownloadFilenameRoute
  ApiV1PlaylistsIdSongsRoute: typeof ApiV1PlaylistsIdSongsRoute
  ApiV1PublicAlbumsIdRoute: typeof ApiV1PublicAlbumsIdRoute
  ApiV1PublicAlbumsIndexRoute: typeof ApiV1PublicAlbumsIndexRoute
  ApiV1AuthPasskeyFlowActionRoute: typeof ApiV1AuthPasskeyFlowActionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/tags': {
      id: '/api/v1/tags'
      path: '/api/v1/tags'
      fullPath: '/api/v1/tags'
      preLoaderRoute: typeof ApiV1TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/posts': {
      id: '/api/v1/posts'
      path: '/api/v1/posts'
      fullPath: '/api/v1/posts'
      preLoaderRoute: typeof ApiV1PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/owner': {
      id: '/api/v1/owner'
      path: '/api/v1/owner'
      fullPath: '/api/v1/owner'
      preLoaderRoute: typeof ApiV1OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/options': {
      id: '/api/v1/options'
      path: '/api/v1/options'
      fullPath: '/api/v1/options'
      preLoaderRoute: typeof ApiV1OptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/footprints': {
      id: '/api/v1/footprints'
      path: '/api/v1/footprints'
      fullPath: '/api/v1/footprints'
      preLoaderRoute: typeof ApiV1FootprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/coding': {
      id: '/api/v1/coding'
      path: '/api/v1/coding'
      fullPath: '/api/v1/coding'
      preLoaderRoute: typeof ApiV1CodingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/categories': {
      id: '/api/v1/categories'
      path: '/api/v1/categories'
      fullPath: '/api/v1/categories'
      preLoaderRoute: typeof ApiV1CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$resource': {
      id: '/api/v1/$resource'
      path: '/api/v1/$resource'
      fullPath: '/api/v1/$resource'
      preLoaderRoute: typeof ApiV1ResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/profile/': {
      id: '/api/v1/profile/'
      path: '/api/v1/profile'
      fullPath: '/api/v1/profile/'
      preLoaderRoute: typeof ApiV1ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/passkeys/': {
      id: '/api/v1/passkeys/'
      path: '/api/v1/passkeys'
      fullPath: '/api/v1/passkeys/'
      preLoaderRoute: typeof ApiV1PasskeysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/notifications/': {
      id: '/api/v1/notifications/'
      path: '/api/v1/notifications'
      fullPath: '/api/v1/notifications/'
      preLoaderRoute: typeof ApiV1NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/moments/': {
      id: '/api/v1/moments/'
      path: '/api/v1/moments'
      fullPath: '/api/v1/moments/'
      preLoaderRoute: typeof ApiV1MomentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/media/': {
      id: '/api/v1/media/'
      path: '/api/v1/media'
      fullPath: '/api/v1/media/'
      preLoaderRoute: typeof ApiV1MediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/comments/': {
      id: '/api/v1/comments/'
      path: '/api/v1/comments'
      fullPath: '/api/v1/comments/'
      preLoaderRoute: typeof ApiV1CommentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/analytics/': {
      id: '/api/v1/analytics/'
      path: '/api/v1/analytics'
      fullPath: '/api/v1/analytics/'
      preLoaderRoute: typeof ApiV1AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/visitor/weather': {
      id: '/api/v1/visitor/weather'
      path: '/api/v1/visitor/weather'
      fullPath: '/api/v1/visitor/weather'
      preLoaderRoute: typeof ApiV1VisitorWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/tags/$id': {
      id: '/api/v1/tags/$id'
      path: '/$id'
      fullPath: '/api/v1/tags/$id'
      preLoaderRoute: typeof ApiV1TagsIdRouteImport
      parentRoute: typeof ApiV1TagsRoute
    }
    '/api/v1/system/status': {
      id: '/api/v1/system/status'
      path: '/api/v1/system/status'
      fullPath: '/api/v1/system/status'
      preLoaderRoute: typeof ApiV1SystemStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/security/$action': {
      id: '/api/v1/security/$action'
      path: '/api/v1/security/$action'
      fullPath: '/api/v1/security/$action'
      preLoaderRoute: typeof ApiV1SecurityActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/profile/send-code': {
      id: '/api/v1/profile/send-code'
      path: '/api/v1/profile/send-code'
      fullPath: '/api/v1/profile/send-code'
      preLoaderRoute: typeof ApiV1ProfileSendCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/posts/$id': {
      id: '/api/v1/posts/$id'
      path: '/$id'
      fullPath: '/api/v1/posts/$id'
      preLoaderRoute: typeof ApiV1PostsIdRouteImport
      parentRoute: typeof ApiV1PostsRoute
    }
    '/api/v1/playlists/import': {
      id: '/api/v1/playlists/import'
      path: '/api/v1/playlists/import'
      fullPath: '/api/v1/playlists/import'
      preLoaderRoute: typeof ApiV1PlaylistsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/passkeys/$id': {
      id: '/api/v1/passkeys/$id'
      path: '/api/v1/passkeys/$id'
      fullPath: '/api/v1/passkeys/$id'
      preLoaderRoute: typeof ApiV1PasskeysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/notifications/unread-count': {
      id: '/api/v1/notifications/unread-count'
      path: '/api/v1/notifications/unread-count'
      fullPath: '/api/v1/notifications/unread-count'
      preLoaderRoute: typeof ApiV1NotificationsUnreadCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/notifications/stream': {
      id: '/api/v1/notifications/stream'
      path: '/api/v1/notifications/stream'
      fullPath: '/api/v1/notifications/stream'
      preLoaderRoute: typeof ApiV1NotificationsStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/notifications/read-all': {
      id: '/api/v1/notifications/read-all'
      path: '/api/v1/notifications/read-all'
      fullPath: '/api/v1/notifications/read-all'
      preLoaderRoute: typeof ApiV1NotificationsReadAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/notifications/$id': {
      id: '/api/v1/notifications/$id'
      path: '/api/v1/notifications/$id'
      fullPath: '/api/v1/notifications/$id'
      preLoaderRoute: typeof ApiV1NotificationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/moments/recent-tags': {
      id: '/api/v1/moments/recent-tags'
      path: '/api/v1/moments/recent-tags'
      fullPath: '/api/v1/moments/recent-tags'
      preLoaderRoute: typeof ApiV1MomentsRecentTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/moments/$id': {
      id: '/api/v1/moments/$id'
      path: '/api/v1/moments/$id'
      fullPath: '/api/v1/moments/$id'
      preLoaderRoute: typeof ApiV1MomentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/media/upload-branding': {
      id: '/api/v1/media/upload-branding'
      path: '/api/v1/media/upload-branding'
      fullPath: '/api/v1/media/upload-branding'
      preLoaderRoute: typeof ApiV1MediaUploadBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/media/upload': {
      id: '/api/v1/media/upload'
      path: '/api/v1/media/upload'
      fullPath: '/api/v1/media/upload'
      preLoaderRoute: typeof ApiV1MediaUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/media/test-connection': {
      id: '/api/v1/media/test-connection'
      path: '/api/v1/media/test-connection'
      fullPath: '/api/v1/media/test-connection'
      preLoaderRoute: typeof ApiV1MediaTestConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/media/stats': {
      id: '/api/v1/media/stats'
      path: '/api/v1/media/stats'
      fullPath: '/api/v1/media/stats'
      preLoaderRoute: typeof ApiV1MediaStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/media/exif': {
      id: '/api/v1/media/exif'
      path: '/api/v1/media/exif'
      fullPath: '/api/v1/media/exif'
      preLoaderRoute: typeof ApiV1MediaExifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/media/download-url': {
      id: '/api/v1/media/download-url'
      path: '/api/v1/media/download-url'
      fullPath: '/api/v1/media/download-url'
      preLoaderRoute: typeof ApiV1MediaDownloadUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/media/$id': {
      id: '/api/v1/media/$id'
      path: '/api/v1/media/$id'
      fullPath: '/api/v1/media/$id'
      preLoaderRoute: typeof ApiV1MediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/links/apply': {
      id: '/api/v1/links/apply'
      path: '/api/v1/links/apply'
      fullPath: '/api/v1/links/apply'
      preLoaderRoute: typeof ApiV1LinksApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/comments/pending-count': {
      id: '/api/v1/comments/pending-count'
      path: '/api/v1/comments/pending-count'
      fullPath: '/api/v1/comments/pending-count'
      preLoaderRoute: typeof ApiV1CommentsPendingCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/comments/batch': {
      id: '/api/v1/comments/batch'
      path: '/api/v1/comments/batch'
      fullPath: '/api/v1/comments/batch'
      preLoaderRoute: typeof ApiV1CommentsBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/comments/$id': {
      id: '/api/v1/comments/$id'
      path: '/api/v1/comments/$id'
      fullPath: '/api/v1/comments/$id'
      preLoaderRoute: typeof ApiV1CommentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/categories/$id': {
      id: '/api/v1/categories/$id'
      path: '/$id'
      fullPath: '/api/v1/categories/$id'
      preLoaderRoute: typeof ApiV1CategoriesIdRouteImport
      parentRoute: typeof ApiV1CategoriesRoute
    }
    '/api/v1/captcha/image': {
      id: '/api/v1/captcha/image'
      path: '/api/v1/captcha/image'
      fullPath: '/api/v1/captcha/image'
      preLoaderRoute: typeof ApiV1CaptchaImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/captcha/challenge': {
      id: '/api/v1/captcha/challenge'
      path: '/api/v1/captcha/challenge'
      fullPath: '/api/v1/captcha/challenge'
      preLoaderRoute: typeof ApiV1CaptchaChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/backup/$action': {
      id: '/api/v1/backup/$action'
      path: '/api/v1/backup/$action'
      fullPath: '/api/v1/backup/$action'
      preLoaderRoute: typeof ApiV1BackupActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/reset-password': {
      id: '/api/v1/auth/reset-password'
      path: '/api/v1/auth/reset-password'
      fullPath: '/api/v1/auth/reset-password'
      preLoaderRoute: typeof ApiV1AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/refresh': {
      id: '/api/v1/auth/refresh'
      path: '/api/v1/auth/refresh'
      fullPath: '/api/v1/auth/refresh'
      preLoaderRoute: typeof ApiV1AuthRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/password': {
      id: '/api/v1/auth/password'
      path: '/api/v1/auth/password'
      fullPath: '/api/v1/auth/password'
      preLoaderRoute: typeof ApiV1AuthPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/me': {
      id: '/api/v1/auth/me'
      path: '/api/v1/auth/me'
      fullPath: '/api/v1/auth/me'
      preLoaderRoute: typeof ApiV1AuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/logout': {
      id: '/api/v1/auth/logout'
      path: '/api/v1/auth/logout'
      fullPath: '/api/v1/auth/logout'
      preLoaderRoute: typeof ApiV1AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/login': {
      id: '/api/v1/auth/login'
      path: '/api/v1/auth/login'
      fullPath: '/api/v1/auth/login'
      preLoaderRoute: typeof ApiV1AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/forgot-password': {
      id: '/api/v1/auth/forgot-password'
      path: '/api/v1/auth/forgot-password'
      fullPath: '/api/v1/auth/forgot-password'
      preLoaderRoute: typeof ApiV1AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/archive/stats': {
      id: '/api/v1/archive/stats'
      path: '/api/v1/archive/stats'
      fullPath: '/api/v1/archive/stats'
      preLoaderRoute: typeof ApiV1ArchiveStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/analytics/$action': {
      id: '/api/v1/analytics/$action'
      path: '/api/v1/analytics/$action'
      fullPath: '/api/v1/analytics/$action'
      preLoaderRoute: typeof ApiV1AnalyticsActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/stats': {
      id: '/api/v1/admin/stats'
      path: '/api/v1/admin/stats'
      fullPath: '/api/v1/admin/stats'
      preLoaderRoute: typeof ApiV1AdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$resource/$id': {
      id: '/api/v1/$resource/$id'
      path: '/$id'
      fullPath: '/api/v1/$resource/$id'
      preLoaderRoute: typeof ApiV1ResourceIdRouteImport
      parentRoute: typeof ApiV1ResourceRoute
    }
    '/api/v1/public/albums/': {
      id: '/api/v1/public/albums/'
      path: '/api/v1/public/albums'
      fullPath: '/api/v1/public/albums/'
      preLoaderRoute: typeof ApiV1PublicAlbumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/public/albums/$id': {
      id: '/api/v1/public/albums/$id'
      path: '/api/v1/public/albums/$id'
      fullPath: '/api/v1/public/albums/$id'
      preLoaderRoute: typeof ApiV1PublicAlbumsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/posts/slug/$slug': {
      id: '/api/v1/posts/slug/$slug'
      path: '/slug/$slug'
      fullPath: '/api/v1/posts/slug/$slug'
      preLoaderRoute: typeof ApiV1PostsSlugSlugRouteImport
      parentRoute: typeof ApiV1PostsRoute
    }
    '/api/v1/posts/by-display-id/$displayId': {
      id: '/api/v1/posts/by-display-id/$displayId'
      path: '/by-display-id/$displayId'
      fullPath: '/api/v1/posts/by-display-id/$displayId'
      preLoaderRoute: typeof ApiV1PostsByDisplayIdDisplayIdRouteImport
      parentRoute: typeof ApiV1PostsRoute
    }
    '/api/v1/posts/$id/navigation': {
      id: '/api/v1/posts/$id/navigation'
      path: '/navigation'
      fullPath: '/api/v1/posts/$id/navigation'
      preLoaderRoute: typeof ApiV1PostsIdNavigationRouteImport
      parentRoute: typeof ApiV1PostsIdRoute
    }
    '/api/v1/posts/$id/episodes': {
      id: '/api/v1/posts/$id/episodes'
      path: '/episodes'
      fullPath: '/api/v1/posts/$id/episodes'
      preLoaderRoute: typeof ApiV1PostsIdEpisodesRouteImport
      parentRoute: typeof ApiV1PostsIdRoute
    }
    '/api/v1/posts/$id/comments': {
      id: '/api/v1/posts/$id/comments'
      path: '/comments'
      fullPath: '/api/v1/posts/$id/comments'
      preLoaderRoute: typeof ApiV1PostsIdCommentsRouteImport
      parentRoute: typeof ApiV1PostsIdRoute
    }
    '/api/v1/playlists/$id/songs': {
      id: '/api/v1/playlists/$id/songs'
      path: '/api/v1/playlists/$id/songs'
      fullPath: '/api/v1/playlists/$id/songs'
      preLoaderRoute: typeof ApiV1PlaylistsIdSongsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/notifications/$id/read': {
      id: '/api/v1/notifications/$id/read'
      path: '/read'
      fullPath: '/api/v1/notifications/$id/read'
      preLoaderRoute: typeof ApiV1NotificationsIdReadRouteImport
      parentRoute: typeof ApiV1NotificationsIdRoute
    }
    '/api/v1/comments/$id/reply': {
      id: '/api/v1/comments/$id/reply'
      path: '/reply'
      fullPath: '/api/v1/comments/$id/reply'
      preLoaderRoute: typeof ApiV1CommentsIdReplyRouteImport
      parentRoute: typeof ApiV1CommentsIdRoute
    }
    '/api/v1/comments/$id/edit': {
      id: '/api/v1/comments/$id/edit'
      path: '/edit'
      fullPath: '/api/v1/comments/$id/edit'
      preLoaderRoute: typeof ApiV1CommentsIdEditRouteImport
      parentRoute: typeof ApiV1CommentsIdRoute
    }
    '/api/v1/comments/$id/approve': {
      id: '/api/v1/comments/$id/approve'
      path: '/approve'
      fullPath: '/api/v1/comments/$id/approve'
      preLoaderRoute: typeof ApiV1CommentsIdApproveRouteImport
      parentRoute: typeof ApiV1CommentsIdRoute
    }
    '/api/v1/backup/download/$filename': {
      id: '/api/v1/backup/download/$filename'
      path: '/api/v1/backup/download/$filename'
      fullPath: '/api/v1/backup/download/$filename'
      preLoaderRoute: typeof ApiV1BackupDownloadFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/totp/$action': {
      id: '/api/v1/auth/totp/$action'
      path: '/api/v1/auth/totp/$action'
      fullPath: '/api/v1/auth/totp/$action'
      preLoaderRoute: typeof ApiV1AuthTotpActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/passkey/available': {
      id: '/api/v1/auth/passkey/available'
      path: '/api/v1/auth/passkey/available'
      fullPath: '/api/v1/auth/passkey/available'
      preLoaderRoute: typeof ApiV1AuthPasskeyAvailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/albums/$id/photos': {
      id: '/api/v1/albums/$id/photos'
      path: '/api/v1/albums/$id/photos'
      fullPath: '/api/v1/albums/$id/photos'
      preLoaderRoute: typeof ApiV1AlbumsIdPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/passkey/$flow/$action': {
      id: '/api/v1/auth/passkey/$flow/$action'
      path: '/api/v1/auth/passkey/$flow/$action'
      fullPath: '/api/v1/auth/passkey/$flow/$action'
      preLoaderRoute: typeof ApiV1AuthPasskeyFlowActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/albums/$id/photos/$mediaId': {
      id: '/api/v1/albums/$id/photos/$mediaId'
      path: '/$mediaId'
      fullPath: '/api/v1/albums/$id/photos/$mediaId'
      preLoaderRoute: typeof ApiV1AlbumsIdPhotosMediaIdRouteImport
      parentRoute: typeof ApiV1AlbumsIdPhotosRoute
    }
  }
}

interface ApiV1ResourceRouteChildren {
  ApiV1ResourceIdRoute: typeof ApiV1ResourceIdRoute
}

const ApiV1ResourceRouteChildren: ApiV1ResourceRouteChildren = {
  ApiV1ResourceIdRoute: ApiV1ResourceIdRoute,
}

const ApiV1ResourceRouteWithChildren = ApiV1ResourceRoute._addFileChildren(
  ApiV1ResourceRouteChildren,
)

interface ApiV1CategoriesRouteChildren {
  ApiV1CategoriesIdRoute: typeof ApiV1CategoriesIdRoute
}

const ApiV1CategoriesRouteChildren: ApiV1CategoriesRouteChildren = {
  ApiV1CategoriesIdRoute: ApiV1CategoriesIdRoute,
}

const ApiV1CategoriesRouteWithChildren = ApiV1CategoriesRoute._addFileChildren(
  ApiV1CategoriesRouteChildren,
)

interface ApiV1PostsIdRouteChildren {
  ApiV1PostsIdCommentsRoute: typeof ApiV1PostsIdCommentsRoute
  ApiV1PostsIdEpisodesRoute: typeof ApiV1PostsIdEpisodesRoute
  ApiV1PostsIdNavigationRoute: typeof ApiV1PostsIdNavigationRoute
}

const ApiV1PostsIdRouteChildren: ApiV1PostsIdRouteChildren = {
  ApiV1PostsIdCommentsRoute: ApiV1PostsIdCommentsRoute,
  ApiV1PostsIdEpisodesRoute: ApiV1PostsIdEpisodesRoute,
  ApiV1PostsIdNavigationRoute: ApiV1PostsIdNavigationRoute,
}

const ApiV1PostsIdRouteWithChildren = ApiV1PostsIdRoute._addFileChildren(
  ApiV1PostsIdRouteChildren,
)

interface ApiV1PostsRouteChildren {
  ApiV1PostsIdRoute: typeof ApiV1PostsIdRouteWithChildren
  ApiV1PostsByDisplayIdDisplayIdRoute: typeof ApiV1PostsByDisplayIdDisplayIdRoute
  ApiV1PostsSlugSlugRoute: typeof ApiV1PostsSlugSlugRoute
}

const ApiV1PostsRouteChildren: ApiV1PostsRouteChildren = {
  ApiV1PostsIdRoute: ApiV1PostsIdRouteWithChildren,
  ApiV1PostsByDisplayIdDisplayIdRoute: ApiV1PostsByDisplayIdDisplayIdRoute,
  ApiV1PostsSlugSlugRoute: ApiV1PostsSlugSlugRoute,
}

const ApiV1PostsRouteWithChildren = ApiV1PostsRoute._addFileChildren(
  ApiV1PostsRouteChildren,
)

interface ApiV1TagsRouteChildren {
  ApiV1TagsIdRoute: typeof ApiV1TagsIdRoute
}

const ApiV1TagsRouteChildren: ApiV1TagsRouteChildren = {
  ApiV1TagsIdRoute: ApiV1TagsIdRoute,
}

const ApiV1TagsRouteWithChildren = ApiV1TagsRoute._addFileChildren(
  ApiV1TagsRouteChildren,
)

interface ApiV1CommentsIdRouteChildren {
  ApiV1CommentsIdApproveRoute: typeof ApiV1CommentsIdApproveRoute
  ApiV1CommentsIdEditRoute: typeof ApiV1CommentsIdEditRoute
  ApiV1CommentsIdReplyRoute: typeof ApiV1CommentsIdReplyRoute
}

const ApiV1CommentsIdRouteChildren: ApiV1CommentsIdRouteChildren = {
  ApiV1CommentsIdApproveRoute: ApiV1CommentsIdApproveRoute,
  ApiV1CommentsIdEditRoute: ApiV1CommentsIdEditRoute,
  ApiV1CommentsIdReplyRoute: ApiV1CommentsIdReplyRoute,
}

const ApiV1CommentsIdRouteWithChildren = ApiV1CommentsIdRoute._addFileChildren(
  ApiV1CommentsIdRouteChildren,
)

interface ApiV1NotificationsIdRouteChildren {
  ApiV1NotificationsIdReadRoute: typeof ApiV1NotificationsIdReadRoute
}

const ApiV1NotificationsIdRouteChildren: ApiV1NotificationsIdRouteChildren = {
  ApiV1NotificationsIdReadRoute: ApiV1NotificationsIdReadRoute,
}

const ApiV1NotificationsIdRouteWithChildren =
  ApiV1NotificationsIdRoute._addFileChildren(ApiV1NotificationsIdRouteChildren)

interface ApiV1AlbumsIdPhotosRouteChildren {
  ApiV1AlbumsIdPhotosMediaIdRoute: typeof ApiV1AlbumsIdPhotosMediaIdRoute
}

const ApiV1AlbumsIdPhotosRouteChildren: ApiV1AlbumsIdPhotosRouteChildren = {
  ApiV1AlbumsIdPhotosMediaIdRoute: ApiV1AlbumsIdPhotosMediaIdRoute,
}

const ApiV1AlbumsIdPhotosRouteWithChildren =
  ApiV1AlbumsIdPhotosRoute._addFileChildren(ApiV1AlbumsIdPhotosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  InstallRoute: InstallRoute,
  LoginRoute: LoginRoute,
  AdminSplatRoute: AdminSplatRoute,
  PostsSlugRoute: PostsSlugRoute,
  ApiV1ResourceRoute: ApiV1ResourceRouteWithChildren,
  ApiV1CategoriesRoute: ApiV1CategoriesRouteWithChildren,
  ApiV1CodingRoute: ApiV1CodingRoute,
  ApiV1FootprintsRoute: ApiV1FootprintsRoute,
  ApiV1OptionsRoute: ApiV1OptionsRoute,
  ApiV1OwnerRoute: ApiV1OwnerRoute,
  ApiV1PostsRoute: ApiV1PostsRouteWithChildren,
  ApiV1TagsRoute: ApiV1TagsRouteWithChildren,
  ApiV1AdminStatsRoute: ApiV1AdminStatsRoute,
  ApiV1AnalyticsActionRoute: ApiV1AnalyticsActionRoute,
  ApiV1ArchiveStatsRoute: ApiV1ArchiveStatsRoute,
  ApiV1AuthForgotPasswordRoute: ApiV1AuthForgotPasswordRoute,
  ApiV1AuthLoginRoute: ApiV1AuthLoginRoute,
  ApiV1AuthLogoutRoute: ApiV1AuthLogoutRoute,
  ApiV1AuthMeRoute: ApiV1AuthMeRoute,
  ApiV1AuthPasswordRoute: ApiV1AuthPasswordRoute,
  ApiV1AuthRefreshRoute: ApiV1AuthRefreshRoute,
  ApiV1AuthResetPasswordRoute: ApiV1AuthResetPasswordRoute,
  ApiV1BackupActionRoute: ApiV1BackupActionRoute,
  ApiV1CaptchaChallengeRoute: ApiV1CaptchaChallengeRoute,
  ApiV1CaptchaImageRoute: ApiV1CaptchaImageRoute,
  ApiV1CommentsIdRoute: ApiV1CommentsIdRouteWithChildren,
  ApiV1CommentsBatchRoute: ApiV1CommentsBatchRoute,
  ApiV1CommentsPendingCountRoute: ApiV1CommentsPendingCountRoute,
  ApiV1LinksApplyRoute: ApiV1LinksApplyRoute,
  ApiV1MediaIdRoute: ApiV1MediaIdRoute,
  ApiV1MediaDownloadUrlRoute: ApiV1MediaDownloadUrlRoute,
  ApiV1MediaExifRoute: ApiV1MediaExifRoute,
  ApiV1MediaStatsRoute: ApiV1MediaStatsRoute,
  ApiV1MediaTestConnectionRoute: ApiV1MediaTestConnectionRoute,
  ApiV1MediaUploadRoute: ApiV1MediaUploadRoute,
  ApiV1MediaUploadBrandingRoute: ApiV1MediaUploadBrandingRoute,
  ApiV1MomentsIdRoute: ApiV1MomentsIdRoute,
  ApiV1MomentsRecentTagsRoute: ApiV1MomentsRecentTagsRoute,
  ApiV1NotificationsIdRoute: ApiV1NotificationsIdRouteWithChildren,
  ApiV1NotificationsReadAllRoute: ApiV1NotificationsReadAllRoute,
  ApiV1NotificationsStreamRoute: ApiV1NotificationsStreamRoute,
  ApiV1NotificationsUnreadCountRoute: ApiV1NotificationsUnreadCountRoute,
  ApiV1PasskeysIdRoute: ApiV1PasskeysIdRoute,
  ApiV1PlaylistsImportRoute: ApiV1PlaylistsImportRoute,
  ApiV1ProfileSendCodeRoute: ApiV1ProfileSendCodeRoute,
  ApiV1SecurityActionRoute: ApiV1SecurityActionRoute,
  ApiV1SystemStatusRoute: ApiV1SystemStatusRoute,
  ApiV1VisitorWeatherRoute: ApiV1VisitorWeatherRoute,
  ApiV1AnalyticsIndexRoute: ApiV1AnalyticsIndexRoute,
  ApiV1CommentsIndexRoute: ApiV1CommentsIndexRoute,
  ApiV1MediaIndexRoute: ApiV1MediaIndexRoute,
  ApiV1MomentsIndexRoute: ApiV1MomentsIndexRoute,
  ApiV1NotificationsIndexRoute: ApiV1NotificationsIndexRoute,
  ApiV1PasskeysIndexRoute: ApiV1PasskeysIndexRoute,
  ApiV1ProfileIndexRoute: ApiV1ProfileIndexRoute,
  ApiV1AlbumsIdPhotosRoute: ApiV1AlbumsIdPhotosRouteWithChildren,
  ApiV1AuthPasskeyAvailableRoute: ApiV1AuthPasskeyAvailableRoute,
  ApiV1AuthTotpActionRoute: ApiV1AuthTotpActionRoute,
  ApiV1BackupDownloadFilenameRoute: ApiV1BackupDownloadFilenameRoute,
  ApiV1PlaylistsIdSongsRoute: ApiV1PlaylistsIdSongsRoute,
  ApiV1PublicAlbumsIdRoute: ApiV1PublicAlbumsIdRoute,
  ApiV1PublicAlbumsIndexRoute: ApiV1PublicAlbumsIndexRoute,
  ApiV1AuthPasskeyFlowActionRoute: ApiV1AuthPasskeyFlowActionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
